basePath: /
definitions:
  handlers.ConfirmRequest:
    properties:
      code:
        example: "123456"
        type: string
      email:
        example: user@example.com
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
      username:
        example: JohnDoe
        type: string
    type: object
  handlers.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Event:
    properties:
      createdAt:
        type: string
      creator_id:
        type: integer
      date:
        type: string
      description:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      main_image:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      user_ids:
        description: Массив ID участников
        items:
          type: integer
        type: array
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        example: user@example.com
        type: string
      events:
        description: Связь с событиями (многие-ко-многим)
        items:
          $ref: '#/definitions/models.Event'
        type: array
      id:
        type: integer
      updatedAt:
        type: string
      username:
        example: JohnDoe
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API для работы с пользователями.
  title: User API
  version: "1.0"
paths:
  /confirm:
    post:
      consumes:
      - application/json
      description: Подтверждает email пользователя с помощью кода
      parameters:
      - description: Email и код подтверждения
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.ConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Подтверждение email
      tags:
      - auth
  /events:
    get:
      description: Возвращает список всех событий
      produces:
      - application/json
      responses:
        "200":
          description: List of events
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
      summary: Получить все события
      tags:
      - События
    post:
      consumes:
      - application/json
      description: Создание события
      parameters:
      - description: Event data
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "201":
          description: Created event
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Создать новое событие
      tags:
      - События
  /events/{id}/participants:
    get:
      consumes:
      - application/json
      description: Возвращает список участников события по его ID
      parameters:
      - description: ID события
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить участников события
      tags:
      - events
  /getUserEvent/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает события пользователя по его ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить события пользователя по ID
      tags:
      - users
  /register:
    post:
      consumes:
      - application/json
      description: Отправляет код подтверждения на email
      parameters:
      - description: Данные для регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /users:
    get:
      consumes:
      - application/json
      description: Возвращает список всех пользователей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Получить всех пользователей
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает пользователя по его ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить пользователя по ID
      tags:
      - users
swagger: "2.0"
